# Generated by Django 3.1.2 on 2021-02-26 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20201230_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='department_id',
            field=models.ForeignKey(blank=True, default=2, on_delete=django.db.models.deletion.CASCADE, to='account.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
