# Generated by Django 3.1.2 on 2021-04-08 16:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0007_auto_20210226_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('time_id', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=20)),
                ('start_time', models.CharField(max_length=5)),
                ('end_time', models.CharField(max_length=5)),
                ('sem', models.CharField(max_length=5)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.department')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subject')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Student_attendance',
            fields=[
                ('attend_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(default=False)),
                ('attend_date', models.DateField(auto_now_add=True)),
                ('attend_time', models.TimeField(default=datetime.time(2, 1))),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.subject')),
            ],
        ),
    ]
