# Generated by Django 3.1.2 on 2021-04-08 19:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20210226_1032'),
        ('Attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetable',
            old_name='subject',
            new_name='subject_id',
        ),
        migrations.RemoveField(
            model_name='timetable',
            name='department',
        ),
        migrations.AddField(
            model_name='timetable',
            name='department_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.department'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='attend_time',
            field=models.TimeField(default=datetime.time(0, 0)),
        ),
    ]
