# Generated by Django 3.1.2 on 2021-04-24 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0002_auto_20210409_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendance',
            name='attend_time',
            field=models.TimeField(default='13:25'),
        ),
    ]
