# Generated by Django 3.1.2 on 2021-05-05 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0003_auto_20210424_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendance',
            name='attend_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student_attendance',
            name='attend_time',
            field=models.TimeField(default='13:31'),
        ),
    ]
