# Generated by Django 3.1.2 on 2021-05-10 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Attendance', '0004_auto_20210505_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_attendance',
            name='attend_time',
            field=models.TimeField(default='00:34'),
        ),
    ]
